services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '15432:5432'

    networks:
      - net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8888:80"
    depends_on:
      - postgres

    networks:
      - net

networks:
  net:
    driver: bridge